### ISSUE TITLE
Which/what version of node.js/io.js do we support?

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/HTML-Client#100]
Related to #99: Travis can run tests on many different version to see that tests pass on all of them.

**Comment by jacwah** [comment]
npm WARN engine karma@0.13.9: wanted: {"node":">=0.10 <=0.12 || >=1 <=3"} (current: {"node":"4.0.0","npm":"2.14.2"})

Karma seems to have some opinions on the matter.

**Comment by danpantry** [comment]
I'd suggest the latest version that karma lets us use. 0.10 is pretty darn old.

**Comment by danpantry** [comment]
[Relevant announcement from Node foundation](https://nodejs.org/en/blog/release/v4.0.0/)

> The collaborators of the Node.js project and the members of the Node.js Foundation are proud to offer v4.0.0 for general release. This release represents countless hours of hard work encapsulated in both the Node.js project and the io.js project that are now combined in a single codebase. The Node.js project is now operated by a team of 44 collaborators, 15 of which form its Technical Steering Committee (TSC). Further, over 100 new individuals have been added to the list of people contributing code to core since v0.12.7.

> Node.js v4.0.0 contains V8 v4.5, the same version of V8 shipping with the Chrome web browser today. This brings with it many bonuses for Node.js users, most notably a raft of new ES6 features that are enabled by default including block scoping, classes, typed arrays (Node's Buffer is now backed by Uint8Array), generators, Promises, Symbols, template strings, collections (Map, Set, etc.) and, new to V8 v4.5, arrow functions.

**Comment by danpantry** [comment]
Related https://github.com/karma-runner/karma/issues/1577

**Comment by jacwah** [comment]
`>=0.10 <=0.12` refers to node.js while `>=1 <=3` refers to io.js, correct? I currently set Travis to use 0.12, but it can easily be modified in .travis.yml.

**Comment by danpantry** [comment]
Yes. Iojs and nodejs are converging now, so them being separate entities is kinda moot. 4 will be the merged branch.

**Comment by Phrancis** [comment]
@danpantry @SirPython Looks like most current node.js is 4.4.1 as of 2016-03-22. See [from ChangeLog](https://github.com/nodejs/node/blob/v4.4.1/CHANGELOG.md#2016-03-22-version-441-argon-lts-thealphanerd). Do we need to do anything with this issue, besides perhaps for documentation's sake?

**Comment by danpantry** [comment]
@Phrancis  wat?

```
$ node -v
v5.3.0
```

The current stable release is 5.9.0

**Comment by Phrancis** [comment]
Uh, wow. I wonder why their changelog shows 4.4.1 ...

**Comment by Phrancis** [comment]
4.4.1 is LTS ("recommended for most users"), 5.9.0 is latest stable release. We may as well use latest stable so we have access to latest features, as long as we can make it work in all modern browers (i.e., not in IE <=9 and other crap browsers like that)
