### ISSUE TITLE
Error messages displayed in chat

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#105]
Currently, in the lobby, if the user tries either to enter the deck builder or a game without an opponent selected and/or a mod selected, an error is displayed *in chat*.

However, now that we have popups for displaying errors, wouldn't it make more sense to display the error there?

Related: #71

**Comment by jacwah** [comment]
Related to Cardshifter/Cardshifter#379

**Comment by Zomis** [comment]
This is a server-side issue, nothing the client can do about it really. I suppose the client already shows error messages when it receives a `ServerErrorMessage` from the server?

**Comment by jacwah** [comment]
The server is not sending `ChatMessage`s for the errors listed above as far as I can tell [see this line](https://github.com/Cardshifter/Cardshifter/blob/3d42ca22854a6c017c30dc841781a4c348dc9958/cardshifter-server/src/main/java/com/cardshifter/server/model/Handlers.java#L56).

There is at least one were a `ChatMessage` is sent though.

**Comment by SirPython** [comment]
I believe a ServerErrorMessage is sent, but before, the HTML client was copying the JavaFX client in that it would display those two specific error messages in the form of a chat message.

**Comment by Zomis** [comment]
That doesn't mean that JavaFX did it the right way ;)

**Comment by SirPython** [comment]
[Fixed](https://github.com/Cardshifter/HTML-Client/commit/6754fdb8a467d139fb79c5d08bf06a796ca1550b)
