### ISSUE TITLE
Two big problems: unit testing and controllers

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#108]
Right now, I see two large problems with this client:
- We don't have unit testing.
- Our controllers are holding too much logic (they need to be refactored into smaller ones)

Which one is more of a problem? Which one should we work on fixing first?

**Comment by SirPython** [comment]
I think that we need to worry about refactoring the controllers first. This may make setting up unit testing a lot easier.

Also, from the[ unit testing guide for AngularJS](https://docs.angularjs.org/guide/unit-testing):

> Angular is written with testability in mind, but it still requires that you do the right thing. We tried to make the right thing easy, but if you ignore these guidelines you may end up with an untestable application.

Right now, as @danpantry has pointed out, we aren't doing the right thing by putting this much logic in a single controller.

**Comment by SirPython** [comment]
Related #72 and [controller-refactoring](https://github.com/Cardshifter/HTML-Client/tree/controller-refactoring)

**Comment by jacwah** [comment]
I think you're rationale for refactoring first makes sense. Keep in mind that everything doesn't have to be done at once - you could refactor and test one controller at a time for instance.

**Comment by danpantry** [comment]
I vote for refactoring out the functionality while writing tests for that functionality, a bit at a time, in small bites. Don't try and refactor the entire controller at once.

**Comment by Phrancis** [comment]
In working on vanilla-js-rewrite, I'm condering testing with [Jasmine](https://dev.to/aurelkurtula/unit-testing-with-vanilla-javascript-the-very-basics-7jm), looks like it would be simple enough if we decided to do that.

**Comment by Phrancis** [comment]
Closing as no longer needed #144

**Comment by Zomis** [comment]
Well, tests are still needed.... ;)

**Comment by Zomis** [comment]
For tests, see #72
