### ISSUE TITLE
What to refactor out of the controllers

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#109]
In #108, it was discussed that the controllers need to be refactored (while being tested along the side).

Here is what the current controllers need to be split up into:
- Login
  - [ ] Logging in handling
  - [ ] Server stats
- Lobby
  - [ ] Chat
  - [ ] Game invite sending/receiving
- Game board
  - [ ] Action handling
  - [ ] Card handling
  - [ ] Player info handling

Any other ideas on what needs to be refactored, what shouldn't be refactored, and what should be combined in the list above?

**Comment by SirPython** [comment]
http://chat.stackexchange.com/transcript/message/24337805#24337805

> Unfortunately I know very little about the web client code, but isn't it possible that not all controllers want to handle errors in the same way?

**Comment by jacwah** [comment]
[It looks like there's been some progress on this](https://github.com/Cardshifter/HTML-Client/compare/controller-refactoring...SirPython:controller-refactoring). What has been done and what is still left to do?

**Comment by SirPython** [comment]
@jacwah The game board controller needs to be refactored. All the other new controllers need to be reviewed (to make sure that they all have everything they need). They need to somehow be included in the module/the HTML.

Note that each "scene" needs at least one "main" controller that will be the first one to load when scenes are changed with `ng-route`. All the other controllers for that scene can be loaded in the HTML via the `ng-controller` attrbriute.

**Comment by Phrancis** [comment]
Related #118

**Comment by danpantry** [comment]
To add:

> Controllers don't handle functionality, they handle the interaction between UI <-> services.
https://chat.stackexchange.com/transcript/message/28458481#28458481

As a result, in React/Redux you would have some stateless components representing the view, container components linking those presentational components to the Redux store/action creators, and have the action creators manipulate all of these actions.

**Comment by Phrancis** [comment]
Closing as no longer needed #144
