### ISSUE TITLE
A way to view all messages sent to and from the server

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/HTML-Client#111]
This should be available on all pages (login, game board, chat etc). I've wanted this feature for a while, it would be very useful for me as a server side developer.

Related to #35, but for development debugging rather than user error reporting.

If possible, I would also like to be able to input hand written messages. This could perhaps be done by exposing a function that can be invoked from the console `window.sendMessage = function(msg) {...}`.

**Comment by Zomis** [comment]
In #110, it was added as console.log messages, is this sufficient? Or what format would be desired for this?

**Comment by danpantry** [comment]
I suggest using something like [debug](https://www.npmjs.com/package/debug) or something that can be removed using dead-code elimination

    if (__DEBUG__) {
      console.log('something')
    }

**Comment by jacwah** [comment]
The debug package seems very useful :+1:

**Comment by SirPython** [comment]
The debug package is now being used as of 32082f4827e473e72902f318c4a645ea3a9c8560

**Comment by Phrancis** [comment]
I'd like to see (and had initially planned to include) a server console which can be displayed in the HTML client as well. I can't imagine it would be very complicated to just pipe the JSON from the game server to a redux store (or some client-side data structure). Any ideas?

**Comment by Phrancis** [comment]
As of Vue.js client #144 all server WebSocket messages are displayed in browser console. We can revisit this if we decide to implement a console for the client, but for now I consider this resolved.
