### ISSUE TITLE
Hide info boxes of cards when a new one is opened and hide box on click away

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#114]
Today, I was playing a game with @Phrancis and I noticed that, as I was clicking the various buttons on the cards to see what the card did, the info boxes would stack up on top of each other:

![Image](http://i.imgur.com/aKBj7xI.png)

I think it would be better if, when one box was opened, the currently open one was closed.

<hr>

Also, because of my familiarity with other things like this (perhaps right-click drop down menus), I find myself trying to click away from the card to hide the info box, similar to how you would hide the right-click menu.

If I am not alone on this, I think it would be nice if the info boxes hid if you clicked away from them.

**Comment by jacwah** [comment]
I agree that how they currently work is a bit unintuitive. I think they'd make sense as hover-over, what do you think?

**Comment by Phrancis** [comment]
This behavior has been fixed in new Vue.js client #144
