### ISSUE TITLE
CardshifterServerAPI and state

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/HTML-Client#116]
I'm trying to untangle the code in `controller-refactoring`, and I think the way the  `CardshifterServerAPI` object works is quite hard to grasp. As far as I understand it, the API object is global, and reinitializing it simply overwrites the old properties of the same object. Is this correct?

What I'd like to do is provide the server where the user is logged in as an Angular factory or similar. If each initialization created an independent object this all would be much simpler to understand. Global state is tricky. 

If multiple instances of the API can be used at once, the server stats code could be parallellized and simplified too, I think.

I'm not very familiar with JS or Angular  so I'd like someone's input on this before I start wreaking havoc.

**Comment by SirPython** [comment]
If multiple instances of the API are created, then (I think) they would not all share the same socket, and you would have to initialize and login with a new one for each socket that you create.

**Comment by jacwah** [comment]
Isn't the API initialized multiple times in the server stats controller? The not sharing the socket was intentional.

**Comment by SirPython** [comment]
@jacwah In the server stats controller, the API is initialized and destroyed every time the stats are refreshed. However, after the user has logged in, the socket remains the same and is not closed until the user leaves the page.

**Comment by danpantry** [comment]
https://chat.stackexchange.com/rooms/16134/conversation/brain-dump-re-websockets-redux

brain dump above

**Comment by danpantry** [comment]
https://chat.stackexchange.com/rooms/16134/conversation/brain-dump-2-re-redux-websockets

moar

**Comment by Phrancis** [comment]
Closing as no longer needed #144
