### ISSUE TITLE
Inconsistent pop-ups

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#117]
In the lobby screen, when you receive an invite to play a game, a box appears at the top of your screen saying that you have received an invite and asks you if you want to play or not.

In any other screen (including this one), if there is an error, a modal pops up and shows you a message.

Is this inconsistency bad? Should we try to focus on only using one or the other?

**Comment by Zomis** [comment]
An invite is not an error.

That said, whether or not to popup invites also in the middle? No idea.

**Comment by Phrancis** [comment]
Probably could have a pop-up for both invites and errors, since they both should try to get a user's attention. This should be simple CSS changes.

**Comment by Phrancis** [comment]
I implemented this in the vanilla-js-rewrite branch by adding a chat message on game invite errors (only visible for the user having the error). Since the other JS branches seem abandoned, I'll close this as completed.
