### ISSUE TITLE
Switching to React

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#118]
I recently started playing around with React and I've quickly realized how great of a tool it is. To sum it up, it basically enforces a modular design and makes rendering HTML and lot easier and a lot more readable.

I think that this code could really benefit from this. As has been stressed, the code right now is not very modular, and there has been some trouble in trying to make it modular. I think that, if we try changing this to use React rather than AngularJS, the code will benefit in that it will be more maintainable.

The code will not have to change much design-wise. While the code itself is not split up into modules, different modules can be easily defined within the code.

**Comment by Zomis** [comment]
Would #88 be easier to accomplish if using React?

**Comment by SirPython** [comment]
I'm not quite sure.

I don't think it will be any easier or harder; it will be different. For one, I don't think the HTML would be able to appear in an HTML file. It would have to appear in a file with something like:

```
ReactDOM.render(
    <mod name="...">
        <player>
        ....
    </mod>,
    document.getElementById("...")
);
```

Where `mod`, `player`, and the other directives you mentioned in #88 (`properties`, `property`, etc) are all React classes/modules.

Would this design/usage make sense?

**Comment by SirPython** [comment]
If there is trouble in the decision, we could always try turning a bit of it over to React and see how it goes.

**Comment by Zomis** [comment]
There are two primary questions I think for this:

- Is it possible to dynamically load any file? (to load a HTML file with the name of the mod if it exists, if it doesn't then load a default one)
- Can it be used as a template, and in turn load other templates? Such as the following (just an example):


<html><h1>Mythos</h1><zone>For each card: <card....></card></zone></html>

That is, use a template within the template. ("zone" and "card" tags above are meant to be some sort of templates)

**Comment by SirPython** [comment]
I think there is a way, but I have not confirmed it.

If the template file was an HTML file that utilized certain React classes/JSX elements that were made for configuration files then it could probably be read like this:

```
ReactDOM.render(
    require("mythos.config"),
    document.getElementById("foo");
}
```
(as an example)

This (maybe) would take the template file, load it, and it would be compiled like regular JSX elements. Then, they would be rendered to the webpage.

Is this what you mean?

**Comment by Zomis** [comment]
The most important question, for #88, is: Can you check if a file exists before you include it, and if it doesn't can you then include a different file?

**Comment by SirPython** [comment]
Probably. I bet if you tried including it and it had a value such as `null`, then you'd know that the file doesn't exist. At that point, you could try to include a different file.

And if that isn't the case, there is probably a node module we could find.

**Comment by SirPython** [comment]
I also think we should switch to React because a new version of Angular is coming out, and switching our code to be using that would be almost as difficult as switching to React, as the new version will not be backwards-compatible (if I'm using that term correctly).

**Comment by danpantry** [comment]
@Zomis With `require`, yes, you can do that, but you should be using ES6 modules; and ES6 modules (`import`) do *not* support this behaviour because they must be the first statements in the file.

Angular2 and Angular1 modules [are compatible with each other](http://blog.thoughtram.io/angular/2015/10/24/upgrading-apps-to-angular-2-using-ngupgrade.html) using ngUpgrade

**Comment by Zomis** [comment]
@danpantry So I can do something like `require(cardName)` where modname is inserted at runtime, and if that file doesn't exist I tell it to `require(cardType)` and if that also doesn't exist I tell it to `require(generalCard)` ? If that's possible, could you show an example of this?

**Comment by danpantry** [comment]
Sorry, I thought you meant at compile-time.. No, `require` won't work in that manner at runtime. I mean, obviously, `require` is used at runtime, but all of the dependencies are resolved at compile time.

**Comment by Phrancis** [comment]
Closing as no longer needed #144
