### ISSUE TITLE
JavaScript Framework

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#119]
Recently there has been some discussion on which JavaScript framework we should really be using. So far, our options are: AngularJS (the one we are currently using) and ReactJS.

Which one should we use? Why? Do you know of any other possible options?

**Comment by SirPython** [comment]
#118 - Why we should switch to React.

**Comment by Zomis** [comment]
For me the most important thing to solve is #88 - Different HTML files for different mods. As long as we can do that, I'm fine with any framework. I'm not sure if AngularJS supports this at all, or if it is just webpack that is currently restricting us.

Also, as I mentioned in #118:

> The most important question, for #88, is: Can you check if a file exists before you include it, and if it doesn't can you then include a different file?

**Comment by Phrancis** [comment]
Closing as no longer needed #144 as we have chosen to go with Vue.js and have implemented the new client.
