### ISSUE TITLE
Notification when a user leaves the server

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#120]
Right now, when a user joins the server, a chat message is spit out saying that the user has joined the server.

It would be nice to also have a message that is sent when a user leaves the server.

**Comment by Zomis** [comment]
Isn't this a server feature, not a HTML-Client feature?

**Comment by Phrancis** [comment]
Submitted [issue](https://github.com/Cardshifter/Cardshifter/issues/429) on the repository which has the server code.
