### ISSUE TITLE
On pressing ? on card list, previous opened cards do not disappear

### ISSUE THREAD

**Issue by AldenPeterson** [Cardshifter/HTML-Client#122]
Seems like opening others should close the previous ones.

Mainly a problem when they overlap.

![image](https://cloud.githubusercontent.com/assets/3105540/12500093/7c5a2366-c075-11e5-9239-2e568a3f4466.png)

**Comment by Zomis** [comment]
No longer an issue as we're using on-hover now.

**Comment by Phrancis** [comment]
Well, it's technically still an issue as we are using both hover and active, so this is still happening, but it would be a simple matter to just remove active. Thoughts?

**Comment by Zomis** [comment]
@Phrancis I'm not able to reproduce the issue now though.

**Comment by Phrancis** [comment]
Ah OK, must have got accidentally fixed lol.
