### ISSUE TITLE
When mousing over stats, if mouse is stopped show a temporary popup with information

### ISSUE THREAD

**Issue by AldenPeterson** [Cardshifter/HTML-Client#123]
Current state: lots of card attributes/etc are not clear to a new player.

If when mousing over for example "attack" it would be nice if when the mouse is held there for a short period that a popup showed something explaining the attribute.

For example, if mousing over health on the Longbowman:

"Health:
2 base + 2 from Healer"

![image](https://cloud.githubusercontent.com/assets/3105540/12500310/88248860-c077-11e5-9b4e-9637490e1984.png)

**Comment by Phrancis** [comment]
Doing this as suggested with "Health: 2 base + 2 from Healer" I believe would require modifications to the server code, as right now the server only tells the client what its stats are, and not why they are that way. We added a mouse-over text for all the buttons that tell what the meaning of the button is, which I think is close enough for now.
