### ISSUE TITLE
Both idiot and loser AI do not draw cards and start with no cards in hand

### ISSUE THREAD

**Issue by AldenPeterson** [Cardshifter/HTML-Client#126]
At game start, both the AI Loser and AI Idiot start with no cards in hand:

![image](https://cloud.githubusercontent.com/assets/3105540/12500674/00387b10-c07b-11e5-96aa-2bb8e912b492.png)

![image](https://cloud.githubusercontent.com/assets/3105540/12500708/3719a79e-c07b-11e5-8522-229083a71eb3.png)

Both continue to not draw cards and take 1 point of damage a turn (regardless of my actions). This may be related or a separate issue.

**Comment by Phrancis** [comment]
@enderland do you recall if that happened for Cyborg-Chronicles or Mythos mods, or both?

**Comment by Phrancis** [comment]
Will try to reproduce this in new Vue.js client, both AI Loser and AI Idiot, and both mods. @Zomis is this by design? Seems based on the server messages I see in the browser console that the server is doing this to the players.

**Comment by Zomis** [comment]
Whoops, how has this been left untouched for two years? I know exactly why this happens, it's a bug in the server.
