### ISSUE TITLE
Changeable Server List

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#129]
The current server list in the login screen is static; the servers you see on that list are stuck there unless you go in and modify the code.

A possible feature would be create a form where users can submit their own servers and possibly remove servers from the list. However, this might look weird with a drop-down menu, so perhaps the form could use some revamping.

**Comment by Phrancis** [comment]
Maybe at some point in the future we can reconsider this, but for right now this is not likely to be useful or needed #144
