### ISSUE TITLE
Changing certain Text

### ISSUE THREAD

**Issue by lol123Xb** [Cardshifter/HTML-Client#132]
Is there any way we can change the text "Mulligan" and "Mana" to something else?
It would be nice if we could, unless there is a way and I haven't found it yet.

**Comment by Zomis** [comment]
The next big step for the client will be to make the client much more moddable, to have custom HTML for each mod for example. Then this should definitely be possible.

Until then, you should be able to modify this line: https://github.com/Cardshifter/Cardshifter/blob/master/extra-resources/mods/Cyborg-Chronicles/Game.groovy#L34 . Changing that line to `MANA = createResource("Java")` should show the resource name as "Java" instead in some places at least (and still using the identifier `MANA` in the mod setup script)

**Comment by lol123Xb** [comment]
Ahhh, so i was doing it correctly. Thanks. It seems I changed wayyyyy to much lines :)

**Comment by Zomis** [comment]
Can you post your `Game.groovy` file? Then I hope I can be of assistance.

**Comment by lol123Xb** [comment]
http://pastebin.com/0Ue69cy4
here it is. though, all i did was change what you said.

**Comment by Zomis** [comment]
Ah, okay, there's a little bit more that needs to be changed apparently.

First of change `MANA = createResource("MORALE")` to `MORALE = createResource("MORALE")`

Then change all `mana` and `MANA` occourences to `morale` or `MORALE` respectively.

Such as the occourances at line 131 and 169.

Then let me know if there are more problems

**Comment by lol123Xb** [comment]
No such property: MANA for class

is what i got

**Comment by Zomis** [comment]
Does it show a more detailed error message, with a stacktrace?

(By the way, out of pure interest, how did you hear about this project?)

**Comment by lol123Xb** [comment]
i think so, i dont really remember.

and i didn't really _hear_ about this project, i was just searching for web based trading card game engines or source and i stumbled upon this project right after i found sandscape.

**Comment by Phrancis** [comment]
Closing as abandoned.
