### ISSUE TITLE
VR/3D-based client?

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#133]
I don't really see the point of this (fun, maybe?) since VR and 3D don't necessarily work with card games (unless we add nice visual effects and such).

[A-Frame](https://github.com/aframevr/aframe) is a framework for easily making 3D/VR scenes. Since it is mostly based around HTML and since we're going to be switching to React, we wouldn't necessarily have to re-write the entire client: we would just make a second sub-set of presentational components that instead use "A-Frame HTML" rather than regular HTML.

That being said, it wouldn't be much of a change in our plan for the design of the client since this will all fit nicely in with React/Redux.

**Comment by Phrancis** [comment]
Realistically this likely won't happen anywhere in the foreseeable future #144
