### ISSUE TITLE
Modify server interface to interact with Redux store

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#134]
The server interface should take the messages it gets from the server and put it in the store. It should also read the store for messages to send to the server.

Look into middleware -- when I knew what this was, I thought it was important to this so it might still be.

**Comment by SirPython** [comment]
https://github.com/Cardshifter/HTML-Client/issues/127

**Comment by Phrancis** [comment]
Closing as no longer needed #144
