### ISSUE TITLE
Sort card columns in deck builder

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/HTML-Client#156]
Long ago there was an attempt to make columns sortable (kind of like in an Excel table) in [card-sorting](https://github.com/Cardshifter/HTML-Client/commits/card-sorting) branch. I doubt there's anything really salvageable in this branch from nearly 3 years ago, but also thought this may be a desirable feature and we could try it out in the new Vue client.

**Comment by Zomis** [comment]
Shouldn't be too hard: https://bootstrap-vue.js.org/docs/components/table#sorting
