### ISSUE TITLE
Improve player display while in game

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/HTML-Client#158]
Right now the player display while in game is kind of bland, and has redundant information:

![image](https://user-images.githubusercontent.com/8539648/40698080-584029e6-639b-11e8-8b52-043b532b256c.png)

This needs to be made both more useful and if possible more attractive.

**Comment by Zomis** [comment]
I made some changes to this to use the Value component, which is also used on the cards. I hope this was an improvement.

**Comment by Phrancis** [comment]
I reckon this looks a lot nicer, but it looks like we introduced a `NaN` bug. Investigating.

![image](https://user-images.githubusercontent.com/8539648/40755562-e7223238-644c-11e8-8f04-19bf8afcd25e.png)

**Comment by Phrancis** [comment]
Easy fix using `v-if`, this is OK to close now.
