### ISSUE TITLE
Value Animations not working with `npm run build`

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/HTML-Client#165]
After using `npm run build`, the Value Animations does not work. But they work fine when running `npm run dev`.

**Comment by Phrancis** [comment]
Could this possibly offer some hints? https://stackoverflow.com/a/47288011/3626537

**Comment by Zomis** [comment]
@Phrancis I don't think so as we're 1) Not using `animations`, we're using transitions. 2) The `Value` component does not have `<style scoped>` (In fact, it doesn't have any `<style>` at all...)

**Comment by Zomis** [comment]
I have analyzed a bit further and it seems like it's the same classes that are used on the DOM element, but in production they are removed after 2 frames, but in dev they are removed after 12 frames (running at 15 frames per second). So the problem seems to be that the animation elements are removed too early.

**Comment by Zomis** [comment]
See https://stackoverflow.com/a/50825756/1310566
