### ISSUE TITLE
Section: Game Board

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/HTML-Client#28]
Functions:

- [x] Cards in Hand
- [x] Mulligan
- [x] End turn
- [x] Get Player data (Name, Health, Mana, Scrap, Cards remaining...)
- [x] Cards in Battlefield
- [x] Cards with available actions (Play, Attack, Scrap...)
- [x] Game over, winning player

Graphical:

- [x] Self hand cards shown, opponent hidden (but count shown)
- [x] Battlefield cards all shown
- [x] Player data sections
- [x] Hand sections
- [x] Battlefield sections
- [x] Highlights for cards with actions available
- [x] Scrap button/icon on applicable cards
- [x] Game over splash
- [x] Buttons for mulligan, end turn, etc.

Future:

- In-game chat area?

![image](https://cloud.githubusercontent.com/assets/8539648/9128902/cd071140-3c9d-11e5-920a-0d3dbe249464.png)

**Comment by Zomis** [comment]
A new [PlayerEliminatedMessage](https://github.com/Cardshifter/Cardshifter/commit/2910928ad135acf29cdccd9afb9eb0a1fef59633) was recently added to the server, would be perfect to react on that. When you receive that message with an id matching your player, you will no longer be able to perform any actions in the game. That message contains information about whether you won or lost also.

**Comment by Zomis** [comment]
I believe that the angular-ui-bootstrap-thingy can be used for this to create some sort of *Modal* that is shown when game is over
