### ISSUE TITLE
Section: Card Model

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/HTML-Client#29]
Functions:
- [x] Card data
- [x] Insertable into Deck Builder and Game Board
- [x] Clickable

Graphical:
- [x] Display organized data
- [x] Pop-up or larger model shows flavor and effect detail
- [x] Front & back of card display (back for Game Board primarily)

Future:
- Card images
- Icons for different values

**Comment by Phrancis** [comment]
Related: [Issue 346 in main repo](https://github.com/Cardshifter/Cardshifter/issues/346).

**Comment by Zomis** [comment]
Does this work good enough for the moment @Phrancis ? Anything else needed?

The back of cards can be fixed very easily if needed. Do we need it? For a player's deck perhaps? Or for opponent hand?

**Comment by Phrancis** [comment]
Yep cars are good to go, if we ever need a back of card it will be very easy to do.
