### ISSUE TITLE
Would we benefit from a github.io repo?

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/HTML-Client#31]
A github.io repo, instead of a standard repo, is a self-hosting web page that supports most if not all client side stuff. It provides web hosting for free and works fine as long as we don't need server-side stuff (except PHP which is also supported, but I don't think we would need either way). 

Here is an example from a website I've reformatted, on my personal repo: https://github.com/Phrancis/phrancis.github.io/tree/master/george-carlin

As rendered: http://phrancis.github.io/george-carlin/bogus-quotes.html

_The content is not really interesting, please focus on the medium._

**Comment by SirPython** [comment]
There is a slight (but very well fixable) problem: GitHub stores all files a `type/text`; this includes JavaScript files. Therefore, when the webpage will try to load the JavaScript files, an error will arise saying something about the MIME type not being correct.

An easy fix: use [rawgit](http://rawgit.com/). This is a very small and easy-to-use service that will transform a JavaScript file located on GitHub into the correct MIME type.

<hr>

How this is used:

Say we are including the Login Controller in the cardshifter.html file. Right now, that looks like this:

    <script src="login/login_controller.js"></script>

As stated above, this will yield an error. To fix this, we would write:

    <script src="https://rawgit.com/Cardshifter/HTML-Client/master/login/login_controller.js"></script>

**Comment by marcandregirard** [comment]
I think the goal of GitHub site were to host a site to show your project. I don't think it's meant to be used as a free hosting service to host apps and others things like that, but I can be wrong. 

I've read a bit of documentation and here is the first deal breaker : 

> Pages are served over HTTP, not HTTPS, so you shouldn't use them for sensitive transactions, like sending passwords or credit card numbers.

I think that at some point in the project we plan to have authentication, so forget that with GitHub site.


@SirPython using rawgit and twisting things like this is not ideal IMO.
