### ISSUE TITLE
What happens during a game

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#43]
This is meant a list for future reference of the kinds of messages that ares sent back and forth between the client and the server during a game.
http://pastebin.com/5Rw7efte

1. The client sends back the [DeckConfig](https://github.com/Cardshifter/Cardshifter/blob/master/cardshifter-api/src/main/java/com/cardshifter/api/config/DeckConfig.java) message showing all the cards that have been selected by the client.

2. The server does some setup.

3. The server sends a few [ZoneChange](https://github.com/Cardshifter/Cardshifter/blob/api-documentation/cardshifter-api/src/main/java/com/cardshifter/api/outgoing/ZoneChangeMessage.java) and [CardInfo](https://github.com/Cardshifter/Cardshifter/blob/api-documentation/cardshifter-api/src/main/java/com/cardshifter/api/outgoing/CardInfoMessage.java) messages. *There is still some confusion about what these are for. Idea: the first cards of your deck that you are given.*

4. [Player info](https://github.com/Cardshifter/Cardshifter/blob/api-documentation/cardshifter-api/src/main/java/com/cardshifter/api/outgoing/PlayerMessage.java) (might be wrong link) about the current client *and* the opponent is sent to both players. 

5. More ZoneMessages and CardInfos

6. A [Reset Available Actions](https://github.com/Cardshifter/Cardshifter/blob/api-documentation/cardshifter-api/src/main/java/com/cardshifter/api/outgoing/ResetAvailableActionsMessage.java) message, and then a [usable action message](https://github.com/Cardshifter/Cardshifter/blob/api-documentation/cardshifter-api/src/main/java/com/cardshifter/api/outgoing/UsableActionMessage.java).

7. This was tested on a bot: The bot mulligan'd, and then 6 was repeated.

**Comment by Phrancis** [comment]
**ZoneChangeMessage**

Hoping to add some details I'm picking up from the server log...

Lines num 152 through 172 look like your player's (`TestAAA`) initial draw of 5 card entities from zone 112 (deck) to zone 113 (hand), with accompanying "FYI" message from the server to the opponent's client letting it know you have these entities (but not giving out any specific data). 

Then from lines num 213 to 223, you see some card entities put back from 113 to 112, with would be mulliganed cards, and some new ones from 112 to 113 which are redraws. 

From there lines num 255-257 you see the AI which is the first card played from hand to battlefield (zone 114). Some more stuff goes on, then at 293-294 you see a card being taken from deck into hand, indicating the start of another turn.

**Comment by SirPython** [comment]
When the client is being told what cards they are being given in the very beginning, this is what happens:

1. Server sends ZoneChange to A.

2. Server sends CardInfo to A, describing the card that was described in 1.

3. Server sends ZoneChange to B, saying that A received a card.

Repeat for as many cards are dealt out initially (in this case, 5)

**Comment by Zomis** [comment]
> The server sends a few ZoneChange and CardInfo messages. There is still some confusion about what these are for. Idea: the first cards of your deck that you are given.

- ZoneMessage is sent to inform the clients about "hey, there's a card zone here!", i.e. general information about a zone that can contain cards. In the future, these messages might be sent later on in the game as well. This sends general information about the entity that owns the zone (might be someone other than a player) and what entity ids the zone currently contains.
- CardInfoMessage is sent to inform the client that "Hey! This is a card that you know about!". It sends along all the public information about that card.
- ZoneChangeMessage represents a single movement of a card from one zone to another

> A Reset Available Actions message, and then a usable action message.

One usable action message is sent for each usable action. For the current mods, the only usable message in the beginning of the game is Mulligan.

**Comment by SirPython** [comment]
@Zomis About this:

> One usable action message is sent for each usable action.

That makes sense, but what is considered a usable action? For example, at least in Mythos, in the beginning a single `UsableActionMessage` is sent for Mulligan, as you said.

However, after that when the game enters normal game-play, the server will send a single `UsableActionMessage` for each card. For example, after Mulligan-ing, I will have 5 cards. For some reason, the server will set 5 `UsableActionMessage`s for each card, where the ID is an ID of one of the 5 cards.

**Comment by Zomis** [comment]
A usable action is a single action that can be used on a single entity.

Examples:

- Mulligan (Player entity) (requires any number of targets)
- End Turn (Player entity)
- Play (Creature Card on Hand)
- Use (Spell Card on Hand) (may require targets, depends on the spell)
- Attack (Creature Card on Battlefield) (requires exactly one target)
- Scrap (Creature Card on Battlefield) (only in Cyborg-Chronicles)

**Comment by Zomis** [comment]
Is this issue cleared out now? Time to close it?
