### ISSUE TITLE
Empty protocol scheme is an antipattern

### ISSUE THREAD

**Issue by danpantry** [Cardshifter/HTML-Client#44]
See [http://www.paulirish.com/2010/the-protocol-relative-url/](here) for more info;

Line 15 of `cardshifter.html` uses an empty protocol scheme. This is bad practice; we should ideally use HTTPS everywhere to prevent MITM attacks. In addition, other urls use the https scheme.

**Comment by jacwah** [comment]
I think you got the link markdown the wrong way around :)

**Comment by danpantry** [comment]
.....oops. Thanks for the catch. [http://www.paulirish.com/2010/the-protocol-relative-url/](http://www.paulirish.com/2010/the-protocol-relative-url/)

**Comment by danpantry** [comment]
fixed with 14cddc0
