### ISSUE TITLE
Show error messages when unable to connect to a server

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#51]
For some reason, the HTML client can only connect to a local server; when ever a connection attempt is made to dwarftowers.com or zomis.net, the client will never connect.

However, when a local server is running, the client connects just fine.

**Comment by SirPython** [comment]
I may be remembering incorrectly, but I do not think this problem was here before.

**Comment by danpantry** [comment]
+1, client appears to time out after a period of time. No immediate error, connection just isn't established.

**Comment by Zomis** [comment]
zomis.net is not running a webserver at the moment. dwarftowers.com might be running an outdated one.

What happens in the client? Is a "Incompatible server" or "Server not responding" message or anything shown?

**Comment by danpantry** [comment]
@Zomis at the time there was no error message. The client would (eventually) time out trying to connect to the websocket.

**Comment by Zomis** [comment]
Then I believe the real issue here is that there are no good error messages shown. The client can't really control which servers are running and which version they are running. If the servers are up and running a matching version, then the client can connect.

**Comment by Phrancis** [comment]
This has been implemented in vanilla-js-rewrite. Since other branches are dormant/abandoned, I will mark this as resolved for now.
