### ISSUE TITLE
Display server statuses on login page

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/HTML-Client#59]
It would be beneficial to have indicators on the login page that show which servers are online and offline, for example:

    stats.zomis.net: ONLINE
    dwarftowers.com: ONLINE
    localhost: OFFLINE

As a bonus, perhaps it could also include an amount of users online, and the latency count for the client.

**Comment by Zomis** [comment]
see the https://github.com/Cardshifter/HTML-Client/tree/server-stats branch for some progress on this

**Comment by Zomis** [comment]
with `play.cardshifter.com` being online, I think this issue is more important.

**Comment by SirPython** [comment]
There is a slight problem with this: In order to keep a feed of active information, the client must constantly be opening up new sockets, closing old ones, and sending ServerQueryMessages for the user count. This seems to me like it could create a big load on the servers.

**Comment by marcandregirard** [comment]
Unless you can make a http "service" method or something that return a json of how many user are currently online. If the service respond then the server is up and you will know how many user are connected. At some point, if we see that this cause some load you just need to cache the request.

**Comment by SirPython** [comment]
The HTML client currently does this:

1. Wait 10 seconds
2. Loop through all the servers
3. Initialize the API to connect to the current server
4. Based on how long the initialization took, determine latency
5. Based on if the socket connected at all, determine if server was online
6. ---Send a server query message---

**Comment by skiwi2** [comment]
To me it looks like a solution consisting of two parts can be used:
1) Poll the server IPs/URLs for information every 30 or 60 seconds, this could be used to show the online/offline status.
2) Then, if a server is online, open a WebSocket connection where you as client request to be informed about user count changes, then whenever an user logs in or logs out, send a message to all subscribed connections that the user count has changed.

**Comment by marcandregirard** [comment]
In the lobby of a server knowing how many user are connected is interesting, but for the login screen when I'm deciding for a server to connect, we don't need to be that precise I think. Just check every 30/60 seconds at the same time we're checking if the server is online is enough. I don't think keeping track of the exact numbers of users is important.

**Comment by Zomis** [comment]
I see no need of continuously updating the value of the number of users online.

Simply opening a WebSocket, requesting the values, then closing the connection, once when you load the page and once every time you click a "Refresh" button should be sufficient. If anyone wants to spam that button continuously, then they can enjoy doing that, I'm quite sure our server can take it. It works for Minecraft, I'm sure it can work for us too.
