### ISSUE TITLE
More dynamic solution for card details in deck builder

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/HTML-Client#60]
https://github.com/Cardshifter/HTML-Client/blob/game-board/src/deck_builder/controller.js#L75

    $scope.showDetails = function(card) {
        var props = card.properties;
        $scope.cardInfo = {
            name: props.name,
            flavor: props.flavor,
            type: props.creatureType,
            health: props.HEALTH,
            attack: props.ATTACK,
            sickness: props.SICKNESS
        };
    };

Some mods have other values than that, some might not even have things like `sickness`. I'd recommend simply copying the properties from `props` to `$scope.cardInfo`

**Comment by SirPython** [comment]
@Zomis I thought about doing that, but there are some cards with properties that I don't think should be seen (I will try to get an example soon). I deemed these as the most important properties, and the HTML takes care of showing the properties: if a property is `undefined`, it will not be shown.

Also, by doing it this way, the order makes sense: on some cards, the name would appear near the middle, and the flavor might be at the bottom; it was very inconsistent.

**Comment by Zomis** [comment]
Well... in a later step, I think that each mod should be able to specify what values that should be shown or not, and how and where they should be shown. For now, I can understand this current approach, but in the long run, it needs to be changed.

this might be related to #29 ?

**Comment by SirPython** [comment]
Yes, I think they are related. I'm not sure of the current status of that right now, but I know that @Phrancis was working on creating a clean design of a card so that all necessary information could be included on it without making the card look ugly; I remember him looking at examples of cards from other games. Read on from [here](http://chat.stackexchange.com/transcript/message/23489785#23489785).

**Comment by Phrancis** [comment]
Also tangentially related to #58
