### ISSUE TITLE
Negative health but still alive

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#65]
I was playing a test game and I noticed that the three "Medusa Snake" cards I had on the field all said "-1/1" on their cards.

Is this a bug?

**Comment by Zomis** [comment]
If it says -1/1, that's -1 *attack*, not health.

**Comment by SirPython** [comment]
Ah, my bad. However, should the attack be -1?

**Comment by Zomis** [comment]
Attack value can go negative, yes. There are some creatures that while in play have an effect on other creatures
