### ISSUE TITLE
Error Displaying

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#71]
Occasionally, an error may happen on the client due to many various reasons. The most common places for errors is in the login screen, where the user could do things like enter an invalid username or mistype a server name in "other".

Right now, a very short and incomplete error message is being displayed via `console.log`. Ideally, a big red box should be shown on the screen with the error message written over it, and an "Okay" button at the bottom. This could probably be achieved with Modals.

**Comment by Phrancis** [comment]
A Modal would look good. Main thing I think would be to get a detailed/more complete error message. Are most of the errors non-Cardshifter specific (e.g., not from the server or client code directly)?

**Comment by SirPython** [comment]
@Phrancis It really depends on the scene. With the new login checking, the login screen would have a lot of errors from the server. However, the lobby screen's errors come from the client itself. For example, the user would see an error if they did not choose a mod before clicking "deck builder".

**Comment by Phrancis** [comment]
Maybe #30 and this would go well together? Perhaps if an error occurs, we could have a pop-up/modal saying `"An error has occurred; see the Console for details." [View] [Dismiss]`

And upon clicking `[View]` just bring up the console the same way we will with the console button? After we identify some of the principal errors we could probably make some client-side formatting to help users understand what they mean, along with "You could try this: ..."

**Comment by Zomis** [comment]
I don't think we need to write error messages to "our" console. My experience of the HTML Client right now is that there are very few error messages. Those error messages that exist (primarily in the login screen, as mentioned), would probably be best solved with a modal.

**Comment by SirPython** [comment]
Modals can get a little complicated, depending on the situation. It might be easier to use [Sweet Alert](https://github.com/t4t5/sweetalert).

An error could be simply displayed with something like `swal("Error!", "Invalid username: cannot contain [more text]", "error")`

**Comment by SirPython** [comment]
[Fixed](https://github.com/Cardshifter/HTML-Client/commit/b7bdd79af01f5a02e64b4a4d15dc8f233f185be3)
