### ISSUE TITLE
Game board impossible to lay out properly with ng-repeat

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/HTML-Client#81]
I've been struggling for a couple of hours trying to get the game board to look like a playable game board. The root of the issue here is the use of `ng-repeat` to make 6 sections in order that have identical HTML/CSS properties. 

- p1 deck (empty), p1 hand, p1 battlefield
- p2 deck (empty), p2 hand (empty/hidden), p2 battlefield. 

This makes both floating and absolute designs practically impossible to control. 

**Floating** 

![floating](http://i.imgur.com/MrO3QLM.png)

Showing `float: right` for the 6 sections with teal border. Same problem with `float:left`, except on the other side. Sections are resized and moved constantly as cards are added and removed from each section. 

**Not floating/Absolute**

![screen shot 2015-08-26 at 10 10 56 pm](https://cloud.githubusercontent.com/assets/8539648/9510978/5d0c1618-4c3f-11e5-976f-cb41add236ee.png)

This is pretty much as bad. The p2 battlefield is literally in front of the p1 battlefield. 

---

I think what really needs to happen here is a completely different approach to the layout. As [@SirPython](http://chat.stackexchange.com/transcript/message/23698444#23698444) suggested:

> Rather than using ng-repeat for each player's zones, you could potentially individually shape out each zone (considering there aren't that many to show: two battlefields, one hand, and the amount of cards in another hand).

I could imagine two possible approaches to that:

- One individual identifier for each of the sections of one HTML file, or;
- One HTML file for each of the sections, that share a common CSS file (and controller?).

Please bring any ideas

**Comment by Phrancis** [comment]
To copy some stuff [from chat](http://chat.stackexchange.com/transcript/message/23699787#23699787), as it is a bit hard to explain better late into the night...

> *Phrn*: Well, put it that way; CSS/HTML is not the problem here, it's just what is making the problem obvious to see.
> *SirP*: What is the problem, then?
> *Phrn*: Making 6 sections with identical properties
> So even if I put it in a table layout, all it would do is create 6 rows with the same properties
> Or 6 tables, lol
> Now, let me ask you; Obviously, the cards in each of the sections would have things that uniquely differentiate them from the cards in all the other sections right?
> User vs opponent, Unplayed vs played, etc.
> *SirP*: Correct.
> *Phrn*: So if it could be setup to filter / funnel / inject the card objects into arbitrarily identified containers, it wouldn't need to dynamically create the containers by iterating over the different sets of things that differentiate the cards?
> i.e., creating the sections as a separate process than putting the cards in them that belong there
> *SirP*: Could you provide an example?
> *Phrn*: Well, let's say we hard-code a ID to some divs, let's just make up user-hand, user-battlefield, opponent-battlefield
> The server already knows and communicates for each card who owns it and where it is, right?
> So as long as we can create containers for the cards that reflect those [card] properties the server handles, we should be able to put the cards where they need to be, regardless of the [HTML/CSS] properties of the container?
> *SirP*: Ah, that makes sense. I think that would be possible.
> *Phrn*: It's less immediately flexible, at least in principle, but I think in practice it would work much better
> Things would start breaking if we had, say, more than 2 players, or added more zones, until we added more containers
> *SirP*: Well, we'll burn that bridge when it comes up.

Hope this provides some ideas for a starting point...

**Comment by danpantry** [comment]
If the issue is a matter of float/positioning use flexbox.

I think you shouldn't be using ng-repeat to create those 6 sections. Are each of these sections functionally identical? Lets take a look at the sections...

> p1 deck (empty), p1 hand, p1 battlefield
> p2 deck (empty), p2 hand (empty/hidden), p2 battlefield.

So.. no, they aren't. Instead, you have 6 sections that each use cards, but each of them have common behaviour. My suggested fix would be something like this.

````html
<section ng-repeat='player in players'>
  <deck></deck>
  <hand></hand>
  <battlefield></battlefield>
</section>
````
layout the positioning using CSS/flexbox. 

alternatively you could try using canvas layouts for the deck instead of DOM (but this makes things tricky with Angular *and* we have to learn how to use canvas which may/may not be supported on mobile devices)

**Comment by Zomis** [comment]
I noticed that in chat you tried to use inline styling on the `<div ng-repeat` tag for all the zones, this will not work.

Each zone is differentiable by the following CSS selectors:

    .player-user .zone-Hand {
    }

    .player-user .zone-Battlefield {
    }

    .player-opponent .zone-Hand {
    }

    .player-opponent .zone-Battlefield {
    }

Using these selectors, I think it might be possible to lay them out more correctly.

**Comment by danpantry** [comment]
@Zomis even if it *does* work, inline styling is just pure crap :( Let's not use it.

Also, can we decide on a standard casing for CSS? The mixed casing there makes me sad. `.player-user` and `.player-opponent` could just as easily be `.opponent` and `.player`, with `.zone-hand` and `.zone-battlefield` being `.hand` and `.battlefield` - semantics are good! This is what I use in my personal projects.

**Comment by Phrancis** [comment]
@Zomis OK I did not realize there were such classes, should have looked a bit more closely. What about the "Deck" zones? AFAIK, those never have anything in them, but they are being created just the same...?

**Comment by Zomis** [comment]
@Phrancis Those zones exists, but are hidden. We can see what to do with them, IMO it would be beneficial to show them somehow, with a pile of cards and a counter for example. But that's another issue.

@danpantry The only bad thing I can think about with not prefixing all zones with `zone-` is that a) it's not immediately clear that it is reserved for a card zone. b) There *can* be naming collisions in the future, for example if a zone was named `player`. Personally, I prefer with the `zone-` prefix.

**Comment by Phrancis** [comment]
Yeah, this is way better.

![screen shot 2015-08-27 at 9 44 39 pm](https://cloud.githubusercontent.com/assets/8539648/9537570/f529862e-4d07-11e5-94d7-bdf96550390b.png)
