### ISSUE TITLE
Allow view of all cards in a game

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/HTML-Client#93]
Allow users to be able to see all defined cards that exists in a mod, in a pretty big size.

This would both provide users with the information about the available cards (even tokens), which in itself is interesting. But it could also allow users to print out the cards and play with them as physical cards, if they would want to.

**Comment by Phrancis** [comment]
This has been implemented in commit 739a0a35.

**Comment by Zomis** [comment]
Related: #154
