### ISSUE TITLE
One-line name and two-line names

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/HTML-Client#96]
This looks a bit odd, because "Exoskeleton" fits on one line, while the others doesn't.

![2015-09-07 16_24_31-cardshifter](https://cloud.githubusercontent.com/assets/1405379/9762511/44ee9d10-5704-11e5-9df4-ea416389a2a0.png)

Any suggestions for what we should do about it?

**Comment by SirPython** [comment]
I think this is exactly what ngFitText is for (if we still use that). I think that if we were to put the title in it's own section (a div?) and apply something from ngFitText to it, it would be automatically shrunk to keep it on one line. @Phrancis would have a better of idea of how to use ngFitText.

**Comment by Phrancis** [comment]
ngFitText lets you select both a minimum and maximum font size. I'm thinking we could set the maximum as what it is now, and set a reasonably low minimum, nothing so small that it couldn't be read well. If a card still spills over, it probably needs a shorter name then. 

The one thing to keep in mind, at least going from memory, is that the div that the text is in has to be of a fixed/absolute size, as that's what ngFitText uses. I'll tinker around with this soon enough.

**Comment by Phrancis** [comment]
Fixed in commit f9b5c696.
